dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-11/run.sh |
  bash
notifications:
  slack:
    secure: UeFpmBl6eWReoibVBip4uX1913XzpTfdUrjmiwLn2HxWE/DQcGszidjmTqpEtvVdQ8zjWJ+npitf5wfB9C/JefvEtoNZ1IT/nCQC+Jw/jcDL6gyEReNuO3Bc+TUWING/Pd0KDhirdcTCKThHGxJrV8wl2vSbGeU7kD3H5O4QQb5CTeR6aqKa5BJPzBVdWaVYvaOYiBW8tbGbPLCesPVmbayQKkS4uTjC1V5PrzKhNgwEmtyEJs3Efg4+nhd/SDCayo0mVvAhU7ZQ0NLC7B5WcQJfcda9kLn1xEMZOJdnWTgp2IynyW1ScRn6mYDEiXPK+47Wv6Ar8g9x/iPvXzYvfgk0DCTFuLzmIP9uxS/4cmaKbxHY9IZH0ea62JBHwnMeaWoXjXwB2PzLmZu6lOB0uXakEDvJFaUc8rLeLQxNki9UHWntx5Xt1sus0yRiQSA//pAciZvXuC6AaioitjfsfFW4K20rAk8larixzvfOMG9xHH5xjHwia+L4Qe458BZzH5sPu8QHCl8NUyBKHK6mCfywtNqLA/dSEdingHCYtQ3phekWHBtoOW36ScoDXSGgrFUYAXAFIRBH57yVMx6WpTLAHnSF9M3BmtdnqPITLSW3XGPA26UTNhOzCc+e+g60rlICXScxQNSMJYUb0tqsJ3EWx0Eg4i0z5V40twkmb78=
