dist: trusty
sudo: required
language: bash

before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-11/run.sh | bash
notifications:
  slack:
   rooms:
    secure: "X0Qd5XHpJZEEbdYFRPmH/Q29DG3JLss1k/TQYT/fonxSb2+Gxtam2H2CjCHqcqCeN0bYoatLoZ6YkQXROUzYCjq6ebkxbUUm+jGUwCaAScYP6aVy64vDiTmUzwZ033hoW+5HuTKJCkFe8HfkkM03l9jqBCFBmSZScAMiyaNFOPDkVkNNsWVKmfdJagkFyw8/zYtxTKWDm9Tjs7G6yq0TG0m8co/EFyKRHeS7Dw8fAkuAYH3IqwoUSrURZP1MN7Rfztf8qvmEja0Ovn4Dh71DrYlqIOM1trrKulw4B/AjVfIb9MKfcKPS5MRRINkL7//lUi3WXObNxKrVtEMoP+gARvmE5R8BZIBDsNDAmoRCNZ76q3AOstNUcgtoVzaPuPXXG/sQyOM6UQKZ20sbAQgLgEomsTnyUyBZK5AfiJ52g30frz3PNxqi51wpHF1J/LZ9nTb0bsXctAvdZpG73jrEpW/+gxCFqZByJ5s6BoGxWdukYAPJBCyeOQJixZaEY/8O+xEVwsPBZaXOUmcwINvD1nBoBe9HOrcExw2Y2OZbElSnaEP8YxMgi0+RgSNl/H6xh00qwBFa9eLHzw98PVGc6DLEYVLt0AsqsF+o9wOILVnruvg3kjEps3PsDHK9p/jpyBCDPKyUp0QcRchuO03oSvbOiYkJZwxm4pmNVaAwcvc="
